# Generated by Django 3.1.4 on 2020-12-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todos',
            options={'ordering': ['-modified_at'], 'verbose_name': 'Todo', 'verbose_name_plural': 'Todos'},
        ),
    ]
